name: Docker CI/CD to EC2

on:
  push:
    branches: [ "master" ] # Triggers whenever you push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Prod Image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: prod  # This uses the 'prod' stage from your Dockerfile
          push: true
          tags: onlysarthak/docker-cicd-h:v1 # Using 'latest' simplifies the Pull step

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Execute Remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to where your docker-compose.yml lives on EC2
            cd ~/docker-cicd-app 
            
            # Pull the new image from DockerHub
            docker compose pull
            
            # Restart services with the new image
            docker compose up -d --no-deps backend
            
            # Clean up old images to save disk space
            docker image prune -f